---
- name: "Installation de Jenkins en natif (avec Java et ouverture de port)"
  hosts: Pipeline
  become: true
  tasks:

    - name: "Mettre à jour les paquets"
      apt:
        update_cache: yes

    - name: "Installer Java (OpenJDK 17)"
      apt:
        name: openjdk-17-jdk
        state: present

    - name: "Télécharger la clé GPG de Jenkins"
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: "Ajouter le dépôt Jenkins à APT"
      copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: |
          deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        mode: '0644'

    - name: "Re-mettre à jour les paquets (avec le dépôt Jenkins)"
      apt:
        update_cache: yes

    - name: "Installer Jenkins"
      apt:
        name: jenkins
        state: present

    - name: "Activer et démarrer Jenkins"
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: "Vérifier si UFW est installé"
      apt:
        name: ufw
        state: present

    - name: "Autoriser le port 8080 (Jenkins)"
      ufw:
        rule: allow
        port: '8080'
        proto: tcp

    - name: "Activer UFW (si non actif)"
      ufw:
        state: enabled
        policy: allow
