- name: Déploiement Grafana OTEL-LGTM
  hosts: local
  become: yes

  tasks:
    - name: Lancer le conteneur OTEL-LGTM
      community.docker.docker_container:
        name: otel-lgtm
        image: grafana/otel-lgtm:latest
        ports:
          - "3000:3000"   # Grafana
          - "4317:4317"   # OTel gRPC
          - "4318:4318"   # OTel HTTP
          - "9090:9090"
        volumes:
          - "otel_data:/var/lib/grafana"
        restart_policy: unless-stopped
        detach: true

    - name: Vérifier le statut du conteneur
      command: docker ps -f name=otel-lgtm
      register: container_status
      changed_when: false

    - debug:
        var: container_status.stdout_lines
