- name: Installer Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Copier les certificats et script
  copy:
    src: generate-certs.sh
    dest: /opt/generate-certs.sh
    mode: 0755

- name: Générer les certificats
  shell: /opt/generate-certs.sh

- name: Copier la config NGINX
  template:
    src: nginx.conf.j2
    dest: /opt/nginx.conf

- name: Déployer le container NGINX
  docker_container:
    name: nginx-proxy
    image: nginx:latest
    state: started
    restart_policy: always
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/certs:/etc/nginx/certs:ro
