- name: Déployer Nextcloud sur Kubernetes
  hosts: application
  connection: local
  vars:
    namespace: default
    pvc_name: nextcloud-pvc
    storage_class: standard
    storage_size: 10Gi

  tasks:
    - name: Créer la PersistentVolumeClaim
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: "{{ pvc_name }}"
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "{{ storage_size }}"
            storageClassName: "{{ storage_class }}"

    - name: Déployer Nextcloud
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nextcloud
            namespace: "{{ namespace }}"
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: nextcloud
            template:
              metadata:
                labels:
                  app: nextcloud
              spec:
                containers:
                - name: nextcloud
                  image: nextcloud:latest
                  ports:
                  - containerPort: 80
                  volumeMounts:
                  - mountPath: "/var/www/html"
                    name: nextcloud-storage
                volumes:
                - name: nextcloud-storage
                  persistentVolumeClaim:
                    claimName: "{{ pvc_name }}"
