---
- name: Déploiement de Prometheus
  hosts: Monitoring
  become: yes
  vars:
    prometheus_version: v2.45.0
    prometheus_port: 9090
    prometheus_data_volume: prometheus-data

  tasks:
    - name: Créer le répertoire de configuration Prometheus
      file:
        path: /opt/prometheus/config
        state: directory
        mode: '0755'

    - name: Créer le fichier de configuration Prometheus
      copy:
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

            - job_name: 'kubernetes-pods'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: replace
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $1:$2
                  target_label: __address__
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - source_labels: [__meta_kubernetes_namespace]
                  action: replace
                  target_label: kubernetes_namespace
                - source_labels: [__meta_kubernetes_pod_name]
                  action: replace
                  target_label: kubernetes_pod_name

            - job_name: 'nextcloud'
              static_configs:
                - targets: ['10.42.0.27:9205']
        dest: /opt/prometheus/config/prometheus.yml
        mode: '0755'

    - name: Créer le volume Docker pour Prometheus
      docker_volume:
        name: "{{ prometheus_data_volume }}"
        state: present

    - name: Créer un réseau Docker pour monitoring
      docker_network:
        name: monitoring
        state: present

    - name: Lancer le conteneur Prometheus
      docker_container:
        name: prometheus
        image: "prom/prometheus:{{ prometheus_version }}"
        ports:
          - "{{ prometheus_port }}:9090"
        volumes:
          - "/opt/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml"
          - "{{ prometheus_data_volume }}:/prometheus"
        command:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--web.console.libraries=/usr/share/prometheus/console_libraries"
          - "--web.console.templates=/usr/share/prometheus/consoles"
          - "--web.enable-lifecycle"
        restart_policy: unless-stopped
        state: started
        networks:
          - name: monitoring

    - name: Vérifier le statut du conteneur Prometheus
      command: docker ps -f name=prometheus
      register: container_status
      changed_when: false

    - debug:
        var: container_status.stdout_lines
